apiVersion: v1
kind: Service
metadata:
  labels:
    app: multiplicar
  name: multiplicar-service
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app: multiplicar
  type: LoadBalancer
