apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: multiplicar
  name: multiplicar-deployment
spec:
  selector:
    matchLabels:
      app: multiplicar
  replicas: 1
  template:
    metadata:
      labels:
        app: multiplicar
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: manuexcd/multiplicar
        name: multiplicar
        resources:
           requests:
              memory: "256Mi"
              cpu: "300m"
        ports:
        - containerPort: 8081