apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: multiplicar-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: multiplicar-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 20
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 20