apiVersion: v1
kind: Service
metadata:
  labels:
    app: sumar
  name: sumar-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: sumar
  type: LoadBalancer
