apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sumar
  name: sumar-deployment
spec:
  selector:
    matchLabels:
      app: sumar
  replicas: 3
  template:
    metadata:
      labels:
        app: sumar
    spec:
      containers:
      - env:
        - name: MICROSERVICES_MULTIPLICAR_URL
          value: http://multiplicar-service:8081/multiplicar/
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: manuexcd/sumar
        name: sumar
        ports:
        - containerPort: 8080
      restartPolicy: Always
